-- Versiones del directorio y migración de pruebas a producción.
--
-- Una versión es una foto numerada de los creadores, las productoras y sus
-- canales, tal como están en ese ambiente en ese momento. Se corta a mano,
-- desde el panel. Producción puede traer una versión de pruebas y aplicarla;
-- para saber qué cambió en cada lado desde la vez anterior, guarda la última
-- que aplicó (la "base") y compara las tres.
--
-- La foto la arma la base de datos, con las funciones de abajo, y el panel
-- hace la comparación. Así el formato se escribe en un solo sitio.

create table versiones (
    numero      integer generated by default as identity primary key,
    nota        text,
    creado_por  text,
    creado_en   timestamptz not null default now(),
    -- La que corta el servidor por su cuenta antes de migrar, para poder
    -- consultar cómo estaba todo justo antes.
    automatica  boolean not null default false,
    contenido   jsonb not null
);

-- Solo en producción: una fila por migración aplicada desde pruebas.
create table migraciones (
    id            integer generated by default as identity primary key,
    version       integer not null,           -- el número que tiene en pruebas
    aplicada_por  text,
    aplicada_en   timestamptz not null default now(),
    -- { base: la versión aplicada, ya con los ids de producción;
    --   ids:  qué id de producción le tocó a cada creador y productora que
    --         nació en pruebas;
    --   resumen: lo que se le enseña a quien migró }
    estado        jsonb not null
);

-- Solo en pruebas: la huella de cada creador y productora tal como estaba la
-- última vez que coincidió con producción (al recibir su copia, o al migrar).
-- Si la huella de ahora es distinta, alguien lo cambió en pruebas y todavía
-- no se ha migrado: la copia que manda producción no debe pisarlo.
alter table creadores   add column sincronizado text;
alter table productoras add column sincronizado text;

-- Los canales de un dueño, en su orden. Con creador, los suyos; sin él, los
-- propios de la productora. No lleva el id del canal: no coincide entre
-- ambientes, y un canal se reconoce por su plataforma y su channel_id o enlace.
create function directorio_canales(de_creador uuid, de_productora uuid)
returns jsonb language sql stable as $$
    select coalesce(jsonb_agg(jsonb_build_object(
                   'plataforma', k.plataforma,
                   'nombre', k.nombre,
                   'url', k.url,
                   'handle', k.handle,
                   'channel_id', k.channel_id,
                   'productora_id', case when k.creador_id is not null then k.productora_id end,
                   'vinculados', (select coalesce(jsonb_agg(v.creador_id order by v.creador_id), '[]'::jsonb)
                                    from canales_creadores v where v.canal_id = k.id))
               order by k.orden, k.creado_en, k.id), '[]'::jsonb)
      from canales k
     where (de_creador is not null and k.creador_id = de_creador)
        or (de_creador is null and k.creador_id is null and k.productora_id = de_productora)
$$;

create function directorio_creador(c creadores)
returns jsonb language sql stable as $$
    select jsonb_build_object(
        'id', c.id,
        'origen_id', c.origen_id,
        'nombre', c.nombre,
        'categoria', c.categoria,
        'bio', c.bio,
        'foto_url', c.foto_url,
        'activo', c.activo,
        'productoras', (select coalesce(jsonb_agg(l.productora_id order by l.productora_id), '[]'::jsonb)
                          from creadores_productoras l where l.creador_id = c.id),
        'canales', directorio_canales(c.id, null))
$$;

create function directorio_productora(p productoras)
returns jsonb language sql stable as $$
    select jsonb_build_object(
        'id', p.id,
        'origen_id', p.origen_id,
        'nombre', p.nombre,
        'descripcion', p.descripcion,
        'logo_url', p.logo_url,
        'activo', p.activo,
        'en_directorio', p.en_directorio,
        'categoria', p.categoria,
        'canales', directorio_canales(null, p.id))
$$;

-- La huella de una ficha. Sin origen_id (enlazarla con producción no es un
-- cambio de contenido) ni la marca `cambiado` que le pone directorio().
create function directorio_huella(ficha jsonb)
returns text language sql immutable as $$
    select md5((ficha - 'origen_id' - 'cambiado')::text)
$$;

-- El directorio entero: lo que se guarda en una versión.
--
-- `cambiado` dice si la ficha tiene cambios hechos aquí que el otro ambiente
-- no conoce: nació aquí, o su huella ya no es la de la última vez que
-- coincidieron. Solo significa algo en pruebas; al migrar, lo que no cambió
-- en pruebas no tiene nada que llevar a producción.
create function directorio()
returns jsonb language sql stable as $$
    select jsonb_build_object(
        'creadores', (
            select coalesce(jsonb_agg(f.ficha || jsonb_build_object('cambiado',
                       f.origen_id is null
                       or (f.sincronizado is not null and f.sincronizado <> directorio_huella(f.ficha)))
                   order by f.id), '[]'::jsonb)
              from (select c.id, c.origen_id, c.sincronizado, directorio_creador(c) as ficha
                      from creadores c) f),
        'productoras', (
            select coalesce(jsonb_agg(f.ficha || jsonb_build_object('cambiado',
                       f.origen_id is null
                       or (f.sincronizado is not null and f.sincronizado <> directorio_huella(f.ficha)))
                   order by f.id), '[]'::jsonb)
              from (select p.id, p.origen_id, p.sincronizado, directorio_productora(p) as ficha
                      from productoras p) f))
$$;

-- Lo que ya está copiado de producción se da por sincronizado tal como está.
update creadores c
   set sincronizado = directorio_huella(directorio_creador(c))
 where c.origen_id is not null;

update productoras p
   set sincronizado = directorio_huella(directorio_productora(p))
 where p.origen_id is not null;
